<!-- Page Header -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="<?=getenv('PROJECT_DESCRIPTION')?>">
        <meta name="author" content="<?=getenv('PROJECT_AUTHOR')?>">
        <link rel="icon" href="<?=getenv('PROJECT_FAVICON')?>">
        <title><?=getenv('PROJECT_NAME')?></title>
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/css/json-viewer.css" rel="stylesheet" type="text/css">
        <link href="assets/css/custom.css" rel="stylesheet" type="text/css">
    </head>
