<!-- Page Nav -->
    <div class="row">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Make Payment</a>
            </li>
            <!--<li class="nav-item">
                <a class="nav-link" id="getStatus-tab" data-toggle="tab" href="#getStatus" role="tab" aria-controls="getStatus" aria-selected="false">Payment Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="expirePayment-tab" data-toggle="tab" href="#expirePayment" role="tab" aria-controls="expirePayment" aria-selected="false">Expire Payment</a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" id="realTimeLog-tab" data-toggle="tab" href="#realTimeLog" role="tab" aria-controls="realTimeLog" aria-selected="false">Real time log</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="confirmURL-tab" data-toggle="tab" href="#confirmURL" role="tab" aria-controls="confirmURL" aria-selected="false">Confirm URL</a>
            </li>
            <!--<li class="nav-item">
                <a class="nav-link" id="returnURL-tab" data-toggle="tab" href="#returnURL" role="tab" aria-controls="returnURL" aria-selected="false">Return URL</a>
            </li>-->
            <li class="nav-item">
                <a class="nav-link" id="document-tab" data-toggle="tab" href="#document" role="tab" aria-controls="document" aria-selected="false">API DocumentL</a>
            </li>
        </ul>
    </div>