<!-- Page Top Nav -->
    <div class="py-5">
        <a href="<?=getenv('PROJECT_SERVER_ADDRESS').getenv('PROJECT_BASE_ROOT')?>">
            <img class="d-block mx-auto mb-4" src="<?=getenv('PROJECT_LOGO')?>" alt="<?=getenv('PROJECT_AUTHOR')?>" width="200">
        </a>
        <h1><?=getenv('PROJECT_TITLE')?></h1>
        <p class="lead"><?=getenv('PROJECT_DESCRIPTION')?></p>
        <h2><?=getenv('PROJECT_VERSION')?></h2>
    </div>